spring:
  application:
    name: scrapper
  codec:
    max-in-memory-size: 500KB
  jpa:
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

app:
  memory-size: 512000

jackson:
  time-zone: UTC

server:
  port: 25000

scheduling:
  fixed-delay: 5000

github:
  base-api-url: "https://api.github.com/"
  media-type: "application/json"

stackOverFlow:
  base-api-url: "https://api.stackexchange.com/2.3/"
  media-type: "application/json"
