app:
  telegramToken: ${TELEGRAM_TOKEN}
  botName: ${BOT_NAME}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG